name: build-and-publish-docs
on:
  push:
    branches:
      - versioning
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://pandoc/latex:2.9
      options: --entrypoint=sh
    steps:
      - uses: actions/setup-python@v2
      - uses: actions/checkout@master
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Install dependencies
        run: |
          pip install sphinx_rtd_theme nbsphinx
          pip install -U git+https://github.com/petergtz/sphinx-multiversion.git@override-version-with-refname
      - name: Build and Commit
        uses: sphinx-notes/pages@v2
        with:
          documentation_path: './docs/source'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
