name: build-and-publish-docs
on:
  push:
    branches:
      - versioning
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - uses: actions/checkout@master
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Install dependencies
        run: |
          pip install sphinx_rtd_theme nbsphinx
          pip install 'git+https://github.com/petergtz/sphinx-multiversion.git@override-version-with-refname'
          sudo apt-get install --yes --quiet pandoc
      - name: Build
        run: ./docs/generate_docs.sh
      - name: Commit and push to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: ${{ github.ref == 'refs/heads/versioning' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dowhy-docs
